name: Build DLL

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake + Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.2.3
          ninjaVersion: latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ env.VCPKG_ROOT }}
          setupOnly: true

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure
        run: cmake --preset release

      - name: Build
        run: cmake --build build/release --parallel

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: FGTweak-dll
          if-no-files-found: error
          path: |
            build/release/FGTweak.dll
